<!--
id: "fawn-shut-bulb"
created: "Tue Sep 30 12:38:32 2025"
attribution: TBA
status: "draft"
chapter: 13
mode: "exercise"
-->

{{< include ../exercise-header.qmd >}}

::: {#exr-fawn-shut-bulb}
Recall that in `r xf("sec-models")`, the SIR model had two parameters: the social **distance** between people and the fraction of infectives who **isolate**. The dynamical rule shown in `r xf("fig-SIR-model-rule1")` is drawn for a social distance of 20 and an isolation fraction of 10%.

One of the flow fields in @fig-another-flow is for a different social distance than in `r xf("fig-SIR-model-rule1")`. The other is for a different isolation fraction. Identify which flow is for each changed parameter and say whether the parameter was raised or lowered. (Note: Both might be lowered, or both might be raised, or one lowered and one raised. You have to figure it out!)

```{r}
#| label: fig-another-flow
#| fig-cap: "Flows for the exercise"
#| echo: false
#| layout-ncol: 2
#| fig-subcap:
#| - Flow (A)
#| - Flow (B)
#| warning: false
highlight <- tibble::tribble(
  ~ S, ~ I, ~ color,
  93000, 0, "brown", 
  21000, 64000, "magenta",
  7500, 85000, "green",
  500, 79500, "deeppink1",
  500, 72000, "deeppink2",
  500, 65000, "deeppink3",
  28000, 50000, "blue",
  35000, 50000, "blueviolet",
  42000, 50000, "violet",
  36000, 29000, "deepskyblue1",
  36000, 22000, "deepskyblue2",
  36000, 15000, "deepskyblue3",)
social <- 20
isolation <- 40
initial <- 100
a <- 0.0003 / social
b <- 0.6 * 80 / (100 - isolation)
vectorfield_plot(dS~ ifelse(S > 100000-I, NA, -a*S*I), dI ~ ifelse(I > 100000-S, NA, a*S*I - b*I), 
                 domain(S= 50:100000, I = 50:100000), 
                 npts = 15, transform = function(x) 10*x^.66)  |>
  gf_point(I ~ S, color = ~ color, data = highlight, inherit=FALSE,
           alpha = 0.45, size = 6, fill = NA) |>
  gf_refine(coord_fixed(), scale_color_identity()) |>
  gf_theme(theme_minimal()) 


# the second flow field
social <- 50
isolation <- 10
initial <- 100
a <- 0.0003 / social
b <- 0.6 * 80 / (100 - isolation)

vectorfield_plot(dS~ ifelse(S > 100000-I, NA, -a*S*I), dI ~ ifelse(I > 100000-S, NA, a*S*I - b*I), 
                 domain(S= 50:100000, I = 50:100000), 
                 npts = 15, transform = function(x) 10*x^.66)  |>
  gf_point(I ~ S, color = ~ color, data = highlight, inherit=FALSE,
           alpha = 0.45, size = 6, fill = NA) |>
  gf_refine(coord_fixed(), scale_color_identity()) |>
  gf_theme(theme_minimal()) 
```

`r devoirs::devoirs_text("fsb-two-flows")`

<!-- Opening answer: fsb-3lj -->
::: {.callout-tip collapse=true `r devoirs:::answer_style()`}
## Answer

Plot (A): Isolation fraction is larger than in `r xf("fig-SIR-model-rule1")`.

Plot (B): Social distance has increased from `r xf("fig-SIR-model-rule1")`.

[..id..]{data-tooltip="Ans id: fsb-3lj"}
:::
<!-- closing answer fsb-3lj -->

:::
 <!-- end of exr-fawn-shut-bulb -->
