---
title: "Short Demography: Preface" 
subtitle: "Reading Questions"
---

```{r include=FALSE}
source("_start-up.R")
```

{{< include _status/draft_DTK.qmd >}}

{{< include _devoirs.qmd >}}

**Note:** For much of human history there was little or no long-term trend in population numbers; whatever population growth occurred was offset by episodes of famine, war, and plague. Starting around the 18th century, population growth became a regular phenomenon. This prompted the emergence of the discipline of *demography*.

Being concerned with the size and growth of population, demography inherently incorporates quantitative reasoning. We will be reading this very short book to provide a natural setting for teaching quantitative reasoning. The course is by no means primarily about demography, but many general patterns of quantitive reasoning are well illustrated by the subject. As well, trends in population are an important aspect of thinking about the interaction of people and natural resources and are a regular feature of news stories and public policy discussions.


-------

The author of the reading points out that world population was mostly steady over thousands of years. In this historical period, she points to a *doubling time* for population, that is, the time interval over which the population doubled in size. Then, near the end of the 18th century, population started to grow much more rapidly. After the early work of John Graunt, interest in demography grew rapidly. Why might interest in demography grow at about the same time as population increase was also growing. (Ans: When things are constant, there's no need to be concerned with the relationships among those things. But in a changing world, understanding the underlying relationships becomes more important.)

Estimate how many people have ever lived from the population figures the author gives. Explain your estimate.

`r devoirs::devoirs_text("RQ-demo-preface-a")`

According to the *Short Introduction*, who estimated that the mortality rate for men does not differ between age 20 and age 40?

`r devoirs::devoirs_text("RQ-demo-preface-b")`

