<!--
id: "goat-forget-hat"
created: "Thu Nov 13 13:48:37 2025"
attribution: TBA
status: "draft"
chapter: 8
mode: "exercise"
-->

{{< include ../exercise-header.qmd >}}



::: {#exr-goat-forget-hat}
[Turn this into an exercise. E.g. ... On the internet, you can find a formula for the heat index
```{r}
#| eval: false
#| label: C08-nfgxf
 HI <- function(T, H) {
-42.379 + 2.04901523*T + 10.14333127*H - .22475541*T*H -
    .00683783*T*T - .05481717*H*H + .00122874*T*T*H +
    .00085282*T*H*H - .00000199*T*T*H*H
}
```
The formula has a visually striking appearance. It is a linear combination of *nine* functions. The formula specifies each coefficient to many decimal places. Impressive!

Or, maybe not. The expert modeler can see what is going on here. The individual functions in the linear combination follow a pattern: T, H, TH, T^2^, H^2^, T^2^H, T H^2, T^2^ H^2^.  Given that humidity cannot be negative and that the domain for temperature where the concept of heat index applies involves only positive temperatures, the functions T and T^2 are hardly different, and similarly for H and H^2. Likewise T H, T^2 H, T H^2, and T^2 H^2^ are all very similar.

Activities based on the stability of the function: what happens when you get a coefficient wrong, or if you leave out one of the functions. The coefficients depend hugely on the units used for temperature (but relative humidity is dimensionless). Demonstration: A simpler formula when T and H are centered on the domain. 

:::
 <!-- end of exr-goat-forget-hat -->
