<!--
id: "squirrel-light-scarf"
created: "Mon Feb 23 17:17:34 2026"
attribution: TBA
status: "draft"
chapter: 15
mode: "outline"
-->

{{< include ../exercise-header.qmd >}}

::: {#exr-squirrel-light-scarf}
We're working with pairs of functions that are closely related to one another:

- $F(x)$ is the anti-derivative of $f(x)$
- $f(x)$ is the derivative of $F(x)$

Our goal is to show you that there is enough information in $f(x)$ to reconstitute $F(x) + C$. The $+C$ means that the reconstitued function might be shifted up or down.

To develop your intuition, we've invented a new way of plotting $f(x)$. @fig-Ffslope shows $F(x)$ and $f(x)$ in the usual format: function output versus input.

The *value* of $f(x)$ at any input value is the same as the *slope* of $F(x)$ at that input value. To help you see this, we have annotated the graph with lines of different slopes. 



```{r}
#| label: fig-Ffslope
#| warning: false
#| layout-ncol: 1
#| fig-cap: "A function F(x) and it's derivative, plotted two ways."
#| fig-subcap: 
#| - "F(x)"
#| - "$f(x) = \\partial_x F(x)$"
#| - "Value of f(x) indicated by segment slope"

f <- dnorm
F <- pnorm
dom <- domain(x = -4:4)

slice_plot(F(x) ~ x, dom) |>
  slope_rose(keepers = "pos", y = 0.05, x = -4, 
             nice_slopes = c(0.1, 0.15, 0.2, 0.25, 0.3, 0.35,0.4), 
             scale = 0.3) |> 
  gf_labs(y = "F(x)") |>
  gf_theme(theme_minimal(base_size = 16))


slice_plot(f(x) ~ x, dom) |>
  gf_labs(y = "f(x) = rate of change of F(x)") |>
  gf_theme(theme_minimal())

Pts <- Znotes::segmentize(F(x) ~ x, h=0.25, dom, npts=1) |>
  dplyr::mutate(top = cumsum(ymax - ymin), bottom=top - (ymax-ymin))

slice_plot(F(x) ~ x, dom, color = "white") |>
   gf_lims(y=c(0, 0.25), x = c(-4,4)) |>
  gf_labs(y="Rise over h = 0.25") |>
  slope_rose(keepers = "pos", y = 0, x = -4, nice_slopes = c(0.1, 0.2, 0.3, 0.4), scale = .06) |> 
  gf_segment(ymin + ymax ~ xmin + xmax, data = Pts,
             color="blue", linewidth=1.5) |>
  gf_theme(theme_minimal())
```

1. In the graph of $F(x)$, locate a specific input---we'll call it $x_0$---where the slope of $F(x)$ is approximately 0.40. Which of these is closest to that input?

`r devoirs::devoirs_set(c(-4, -2, 0, 2, 4), correct = 0, id="sls-1-exls")`

2. Now look at the graph of $f(x)$. An any input value $x_0$, the output $f(x_0)$ is the slope of $F(x)$.  Look at the value of $f(x_0)$, that is, the value of $f()$ at the input you selected in question (1). The output value $f(x_0)$ should match the slope of $F(x)$ at $x = x_0$.

`r devoirs::devoirsTF(TRUE, id = "sls-2-4kse")`

3. Focus now on panel (c) of @fig-Ffslope. This panel also shows $f(x)$, but in a new way. In panel (C), the output of $f(x)$ is shown as the slope of a sloping line segment. (In constrast, in panel (B) the output of $f(x)$ is shown on the vertical axis.) We've annotated the graph with slopes, but it's easier to do a little calculation to find the slope of any of the segments in panel (C).

Slope is rise over run. The segments in panel (C) are drawn with a *run* of 0.25. That means you can read off the slope of a segment by measuring the height ("rise") of the segment and dividing it by 0.25.

What is the slope of the center segment---the tallest one---in panel (C)?

`r devoirs::devoirs_set(c(0.25, 0.3, 0.4, 0.5), correct = 0.4, id="sls-3-lsx")`

4. Judging from the heights of the segments in panel (C), locate the left-most segment that has a slope of 0.1. (Remember that the "run" is 0.25, so the height of the correct segment will be such that height/0.25 = 0.1.) What is the value of $x$ where this segment is located?

`r devoirs::devoirs_set(c(-3, -1.7, -1.1, -0.5), correct = -1.7,
id ="sls-4-ews")`

5. Going back to panel (B), read off the value of $f(x)$ at the input you identified in question (4). What is this value?

`r devoirs::devoirs_set(c(0.1, 0.2, 0.3, 0.4), correct = 0.1, id="sls-5-u3w")`

Connecting the segments in panel (C), so the left end of one segment matches the right end of the neighbor on the left side, reconstitutes the original function $F(x)$, using only the information that's contained in $f(x)$.

:::
 <!-- end of exr-squirrel-light-scarf -->
