<!--
id: "aspen-serve-painting"
created: "Tue Dec  9 17:10:49 2025"
attribution: TBA
status: "ready-to-use"
chapter: 12
mode: "activity"
-->

{{< include ../exercise-header.qmd >}}



::: {#prp-aspen-serve-painting}
Classroom activity for Bayes.

Hand out pictures of crazy probability distributions, one for each student. You can generate them with code like the following, which produces a probability density on the interval -3 to 3.

An example:
```{r}
#| label: C12-sovje
raw <- mosaicCalc::doodle_fun( ~ Q, seed = 8932)
tmp <- argM(raw(Q) ~ Q, domain(Q=-3:3))
tmp2 <- range(tmp$.output.)
tmp3 <- Integrate(raw(Q) - min(tmp2) ~ Q, domain(Q=-3:3))
myfun <- function(Q) (raw(Q) - min(tmp2)) / tmp3
slice_plot(myfun(Q) ~ Q, domain(Q=-3:3)) |>
  gf_theme(theme_minimal())


```

1. Hand out the probability distributions, telling them that this is the hypothesis they have been asked to investigate based on the data which we will generate experimentally. Although these are made-up at random, please take them seriously for the sake of this activity. And, in the spirit of being serious, ask them to carefully examine the hypothesis, weigh the pros and cons, and assign to it a prior probability between 0 and 1. They can be boosters or skeptics of the hypothesis they have been assigned, picking the prior correspondingly.

2. Now we are going to do an experiment to collect data. It will cost us $10,000 for each experimental run, each of which will generate a single value for the "fine-structure magnetic monopole moment" of helium-3. We only have $50,000 in our budget, so we will do five runs of the experiment.
    
    Here are the results from each of the five runs. `r round(runif(5,-3,3), 1)`
    
3. Calculate the likelihood of each of the experimental values under their hypothesis. Then by multiplying those likelihoods together, combine them together into an overall likelihood for the set of five values. Write this on their paper. 

4. Then multiply the likelihood in (3) times the prior they assigned to their hypothesis. This gives the posterior for their hypothesis. 
    
    Poll the class: Which hypothesis is the winner? Are there any hypotheses that can be practically ruled out? If so, ask them to explain what it was that caused such poor performance for their hypothesis.
    
    

:::
 <!-- end of prp-aspen-serve-painting -->
