---
title: "Child mortality and GDP"
---

```{r include=FALSE}
source("../_exercise_startup.R")
library(ggiraph)
library(LSTbook)
library(ggformula)
csvname <- "../../../QuantitativeArgumentation/www/child-mortality-gdp-per-capita.csv"
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| results: hide


raw <- readr::read_csv(csvname)

goo <- raw |> select(Entity, Year, `Child mortality rate`, `GDP per capita`) |>
  filter(Year %in% c(1960,2020)) |>
  na.omit() |>
  mutate(year = as.factor(Year)) |>
  filter(n() == 2, .by = Entity) 

Cuba <- goo |>
  filter(Entity %in% 
           c("Cuba", "Algeria", "Bolivia", 
             "Botswana", "Brazil", "Canada", "Chad", "Chile",
             "Congo", "Eswatini", "Gabon", "Ghana", "Germany",
             "Democratic Republic of Congo"))

P0 <- goo |> 
  gf_point_interactive(`Child mortality rate` ~ `GDP per capita`,
                       color = ~ year, alpha = 0.6,
                       tooltip = ~ glue::glue("{Entity} {Year}<br>GDP {signif(`GDP per capita`, 3)}<br>Mortality  {round(`Child mortality rate`,1)}")) |>
  gf_labs(y = "Child mortality rate (per 1000)", x = "GDP per capita (International Dollars)") 

P1 <- P0 |>
gf_line_interactive(`Child mortality rate` ~ `GDP per capita`, group = ~ Entity,
           color = "black", data = Cuba, inherit=FALSE)

# Not using this. Perhaps use in an exercise.
P2 <- goo |> 
  mutate(logChild = log10(`Child mortality rate`),
         logGDP = log10(`GDP per capita`)) |>
  gf_point_interactive(logChild ~ logGDP, 
                       color = ~ year, alpha = 0.6,
                       tooltip = ~ glue::glue("{Entity} {Year}<br>GDP {signif(`GDP per capita`, 3)}<br>Mortality  {round(`Child mortality rate`,1)}")) |>
  gf_labs(y = "Magnitude of child mortality rate (per 1000)", x = "Magnitude of GDP per capita (International Dollars)") |>
  gf_line_interactive(log10(`Child mortality rate`) ~ log10(`GDP per capita`),
          group = ~ Entity, color = "black", data = Cuba, inherit=FALSE)

P3 <- P1 |> gf_refine(scale_x_log10(), scale_y_log10())
```

```{r}
#| label: ch05-r-61aa6861
#| echo: false
#| message: false
P1 |> gf_girafe()
P3 |> gf_girafe() 
```
